package com.soluti.projecttest.rules

import com.soluti.projecttest.model.Order

rule "MasterCard"
    when
        orderObject : Order(cardType == "MasterCard" && price >= 10000.0)
    then
        orderObject.setDiscount(10);
end

rule "Visa"
    when
        orderObject : Order(cardType == "Visa" && price >= 15000.0)
    then
        orderObject.setDiscount(8);
end

rule "AmericanExpress"
    when
        orderObject: Order(cardType == "AmericaExpress" && price >= 15000.0 )
    then
        orderObject.setDiscount(15);
end